
import ContactForm from "./_components/ContactForm"
import Hero from "./_components/Hero"



export const metadata = {
  title: 'Contact Us',
  description: 'Generated by create next app',
}

export default function Contact() {
  return (
  <>
      <Hero />
      <ContactForm/>
  </>
  )
}
