import Hero from "./_components/Hero"
import ProductsSection from "./_components/ProductsSection"


export const metadata = {
  title: 'Jaeda & Associates',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
  <>
<Hero/>
<ProductsSection/>
  </>
  )
}
